// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFvr4uxFtdGNzZVGNHxVlO7PFis4iYrIQ',
    appId: '1:808192790957:web:21b799496455d9cb48d124',
    messagingSenderId: '808192790957',
    projectId: 'gem-nest-mobileapp',
    authDomain: 'gem-nest-mobileapp.firebaseapp.com',
    storageBucket: 'gem-nest-mobileapp.firebasestorage.app',
    measurementId: 'G-H0T4B201WS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRJYfUAP7g4Soqb_04WrSjxe_ue4fDATE',
    appId: '1:808192790957:android:433d3cd003e9570848d124',
    messagingSenderId: '808192790957',
    projectId: 'gem-nest-mobileapp',
    storageBucket: 'gem-nest-mobileapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8qXclS1VoYpDoStCC9fObP-2GHTRRZBc',
    appId: '1:808192790957:ios:98b9021d2e3e973848d124',
    messagingSenderId: '808192790957',
    projectId: 'gem-nest-mobileapp',
    storageBucket: 'gem-nest-mobileapp.firebasestorage.app',
    iosBundleId: 'com.example.gemnestMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8qXclS1VoYpDoStCC9fObP-2GHTRRZBc',
    appId: '1:808192790957:ios:98b9021d2e3e973848d124',
    messagingSenderId: '808192790957',
    projectId: 'gem-nest-mobileapp',
    storageBucket: 'gem-nest-mobileapp.firebasestorage.app',
    iosBundleId: 'com.example.gemnestMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFvr4uxFtdGNzZVGNHxVlO7PFis4iYrIQ',
    appId: '1:808192790957:web:d81756da7757aae648d124',
    messagingSenderId: '808192790957',
    projectId: 'gem-nest-mobileapp',
    authDomain: 'gem-nest-mobileapp.firebaseapp.com',
    storageBucket: 'gem-nest-mobileapp.firebasestorage.app',
    measurementId: 'G-B078MGYS3W',
  );
}
